steps:
  - group: ":open_book: Build & Deploy Documentation"
    if: build.message !~ /\[skip docs\]/ && !build.pull_request.draft
    steps:
      - label: "Tutorial Build [%N/%t] CUDA Runners"
        key: "tutorial-build-cuda"
        parallelism: 4
        plugins:
          - JuliaCI/julia#v1:
              version: "1"
        command: julia --code-coverage=user --color=yes --project=docs --threads=auto docs/tutorials.jl
        env:
          TUTORIAL_BACKEND_GROUP: "CUDA"
        agents:
          queue: "juliagpu"
          cuda: "*"
        artifact_paths:
          - "docs/src/tutorials/beginner/**/*"
          - "docs/src/tutorials/intermediate/**/*"
          - "docs/src/tutorials/advanced/**/*"
          - "tutorial_deps/*"
          - "**/*.cov"
        timeout_in_minutes: 120

      - label: "Tutorial Build [%N/%t] CPU Runners"
        if: build.message !~ /\[skip docs\]/ && !build.pull_request.draft
        key: "tutorial-build-cpu"
        parallelism: 4
        plugins:
          - JuliaCI/julia#v1:
              version: "1"
        command: julia --code-coverage=user --color=yes --project=docs --threads=auto docs/tutorials.jl
        env:
          TUTORIAL_BACKEND_GROUP: "CPU"
        agents:
          queue: "juliaecosystem"
          os: "linux"
          arch: "x86_64"
        artifact_paths:
          - "docs/src/tutorials/beginner/**/*"
          - "docs/src/tutorials/intermediate/**/*"
          - "docs/src/tutorials/advanced/**/*"
          - "tutorial_deps/*"
          - "**/*.cov"
        timeout_in_minutes: 120

      - label: "Final Documentation Build"
        depends_on:
          - "tutorial-build-cuda"
          - "tutorial-build-cpu"
        plugins:
          - JuliaCI/julia#v1:
              version: "1"
          - JuliaCI/julia-coverage#v1:
              codecov: true
              dirs:
                - src
                - ext
          - sv-oss/node-n#v0.1.2:
              node-version: v20
        command: |
          export LD_LIBRARY_PATH=/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH

          echo "+++ :node: Instantiate NPM"
          cd docs/
          npm i
          cd ..

          buildkite-agent artifact download "**/*" . --build $BUILDKITE_BUILD_ID

          julia --code-coverage=user --color=yes --project=docs -e '
            println("--- :julia: Instantiating project")
            using Pkg
            Pkg.instantiate()
            println("+++ :julia: Building documentation")
            include("docs/make.jl")'
        agents:
          queue: "juliagpu"
          cuda: "*"
        env:
          JULIA_DEBUG: "Documenter"
        timeout_in_minutes: 120

env:
  LUX_DOCUMENTATION_NTASKS: 1
  DATADEPS_ALWAYS_ACCEPT: true
  JULIA_PKG_SERVER: ""
  JULIA_NUM_THREADS: 4
  GKSwstype: "100" # https://discourse.julialang.org/t/generation-of-documentation-fails-qt-qpa-xcb-could-not-connect-to-display/60988
  SECRET_CODECOV_TOKEN: "jQ0BMTQgyZx7QGyU0Q2Ec7qB9mtE2q/tDu0FsfxvEG7/zOAGvXkyXrzIFFOQxvDoFcP+K2+hYZKMxicYdNqzr5wcxu505aNGN2GM3wyegAr+hO6q12bCFYx6qXzU9FLCCdeqINqn9gUSSOlGtWNFrbAlrTyz/D4Yo66TqBDzvaLL63FMnhCLaXW/zJt3hNuEAJaPY2O6Ze1rX2WZ3Y+i+s3uQ8aLImtoCJhPe8CRx+OhuYiTzGhynFfGntZ0738/1RN4gNM0S/hTC4gLE7XMVBanJpGh32rFaiDwW4zAyXKBrDkL3QA3MS1RvLTJxGJ085S16hCk0C4ddAhZCvIM9Q==;U2FsdGVkX1+bXdFeKMs5G79catOCyby2n07A2fg0FjVAvrjQLZ0yfvDS4paJiFikLkodho0khz2YALKb2Y0K6w=="
  SECRET_DOCUMENTER_KEY: "cLvgfo9CJ+ucTQEYaFrAzVBBejzJCxdTz/g4V32WZlEYZzSkjlVed2o6iL1/mXol/c0Ch4f1L4rRWwYb/BF2QGkgQ4idQ5pTYiEjzTCAHiguY8JUEt6kJ5meefJ4Z72pyiBB/hh0hER1r67Lc41aAjlFHitNkwwhbnPW+wV24nqml1o6FkdkLPBGxdKLDuhPfO3LeG6eGcaaQrma9oY5LiJx4GiZNquDQUzHwaPlaGwNk5SPLCFsqUj+AGZRzw27sWtkh0UU2woqIQAqPsJpxSWIKL1uzdgD+tyPtY8NXgi821KLG/nKcBJOv4XUI5TcVJJDqk7sNqyZI4uFiclS2g==;U2FsdGVkX18XRFlmHZmhK1icwRIzDbcAuUQf+zppncfAg10KDYqpUnem5NwayyH+hDuHvDfiW7SPtS96mVTOB77f8J8jG9s7bB9Gpqkv/blqKMtd9AO7yePOxBuPhDor8734S9IllHTNw5Ugr4CG3rUTd0pbyZC3eN961w/O5k1U8n6FvR4CY/8hqzUL/IFXwNbwPbSzdAtqEVL+AGYSx1GUN2HFEvR6oKh8EKJ3/GPZAw2e8vUNfZJbSKgZPhup7mtSg1/93MyyxJMwqAmunYq0pBqW1V4lln1yWRO8rt9lOOf8xwuYP4nHcaFLDYYSIiVm/zHKcTEO4YkbCw56vOGEja/C5XmbCDGtk1j/xhlep/0Ix48IcojK4FPleZpVu5qljJRy55bwL4vbfvbYo/NdXAdR8HiPi4gVtamOhes+Cc672nHBVnTMZ8S+rD6x4bvnKVWI5Ro8fR0sPeHaeCCpAdYHwc7tAzFjXkRDsQOU/YD2Xes2z+iWkz9jm3IyxTE0R801XzU9ijRX2fP/AZ+pjO3Krm1Q247efgU8tNSaIeq0hpTR/QQ57nOSNHWerlVig8AvbqXMq3PuMtRN0QjrA2EDLYLaCEBCb3OjYzh9mQkPrjff5LawWx9Mi10cLNLmogT4RdJPpTqTlJd3Og754fiI73eMww9eovdz87WPBf9fSPLsipvQpyJhBTtpU8JALdkHJcnziVafz99jla4Z+ZzJjJxh0LQTHZCw0DibK7mzKeMjelUWqRTYG4RdX1WwJKCEfjpFwA+njCNFVBAAgfxjonyz8XocVVB6L+r4viqiX6Fy/Y+znxxveTyuN6D2lZ7EQOQLamPMiWYksSBpCkZlC34GpaahSrqNfvdJFH6zXFbcbzhEWJQ417WaDuahAS0eoA+EwsxjcZs+xj/6plj+G+C3AsCUtRfkavPN2BoIXCmy6WHYENh+JYGNe0lsHkI8Q1TNJF7ODLzQgIj7Rdv8izjxUlWvxd1I62+JNgBFM+lLEzWL+yUMqclkJ+VEbCtV92sLGUHeVZ01Bw+bBQLd9kERXpbGcd7xDbnNIF885XiGudox/zgo5AN6OcpwdyVqRGWGTZW51c2ZNs6gxs7joKLWnrt8MwF4BT1nEyTfK0cnGSHimpaNx65oHq2lIGGiKlTvqROyP1pqDKVrzvrNVPytnjQpX2si5W4pwrRfX5t6aZu+A7Fpc7MBUn4onuoAOb5UuW/YGZB3mYq84giLJAkiXX1rDMzADY/iWPhZcGbB/n2SBNLuvGo1nNoo92yUFbQON0L07KGcFs6EO39kfZm5K9YHfbpn0D7lMehghpBVT1iDEyKE6uzS9KFrh1FULZMsiOo1eWw+X13p7ldz7glIyDed5ZE73nmksEr2ZyL5G5ydD3gXn6pzcdoiWSXRQD7fbCg/8dDsYyHBgW2PaLN5M8RpH7ylPe554GUYUxVV8t5scMx9ef0WHVT3A/TACRrJoBZTJnzV/u6dbaM42dx9TOx0rvlwD711HX7oI2CBu0EUDHZExaQxqm7li3WLItQ96xzLyaGOwu52IiMSaHQ2xJV5lmoyxEbHaW/JlwLGHvdHPlnz1/2V2bG74LXaeAZRG8FrvlxnHX1KNLsI9ois94xMgDKAYlTlR7K7jdKlhXx3T/7iKiZHav4tii4SgGt2wydp1n+N5XcAlutcp4OD38oR7S+1BSu+Oe+4MXKXKe4tJG+auwTcXhB3sEUSxr5eDUSVMcnK7p1L9Jd83C+ZY723bQVkjuL1BvB6OAMEaBSlikxHlLuLStAGsCEK49ijTsZ/bNWI8cAs2nF3M4y1Y6jF9z2htxyrxXbGa/GirPXCgwY4/ZauvAC6/oaOmusyftc9Ti1ciOXEZy0Jnn7U6iu4Tlf2L8Mw4PfxmkRKtfszS3DvSVIguMtAuv6v8gCIuJ3ezTDGFqRwyD6QBLy6nyuEnanonagiLhv89+jtkpy5TP5iPoUQX57zzeQwV2XbZ7LM46M/Fs0H5WJB6COggd9gz2/DpFAm1L72RoOvyGWYjzErprvk0UDdtkBWfGyjRtCz+Y37wmHMRk0kUbgx6hs6Va3XbOLq3/wCogVKgAmL93zlhdARvJNzd7Bz09VqbI32ALuk+QXFZeqnUs6oKTQ+wJk0emeeTJYGI3unqgQLDve/ALvAEK53Pkfq5JGB1ZWF0L6HRTdKRSw8K0pWvSBJjpvJg8ubhvJwSiTy5CUak6KOvnyKUQ9g7g98w5t/4+6aV2Dg2qYifRqhtFm69qY2w85NE4fQiD4v8HTkIhSfiapAm1cnrM5euCjyA51JJ6QrhmemIVyIYfQzGUgBENxPxJ5aUJO0/aC9+PzS++JUDT+1m/9BZecDbAc6290FTXCzD/emZ2tgbCd2SKeDvsRouDrBR6rL+gxViEwc1/RXsbcMrnmxl4pOyLQRgyU2YYzBt1neRdeUikr1kr9bSDDtc70309XPnWZOG5cq8jxpm/71/l/kyPeIPCx9CwGfTiUx8Xk9E3YVSt0XhXUf4AoVSpcmLNn7UHgXGCKU30G91jJHzk4J9SqNcYakrdJHf16Hp+Js82ZRF026l2o+sdpDTubnqVUDJV8SqJo1vhLYXkJJeePfjELzuJDYceLaizmC8EKquFLWW1Dxcf/Ax8owt6lVNb3EqYmvmmZEq9IG7E803EpWWzKqyU/7xn+vFceZucUaV6FlCQaiMtqM6FGbwhf2s7MXW9qNu4QrUu8IPLX8KZc+BdPta0HYQmoya7mHSazXkG/L2ZWdj2CmlBxon4MhYISebsoqCxwaF0hcNphh1jtVGEB03zG1VFe4UBSWgbJYIunGebb9my5twilaKpUHeKPZHZ6O+AhwYScZj7B2u8P2wpTajYGrXm8wKnm3HI8Qcf1O0hw0JRAeeltdrRQ4dhVjN5eXcdsoOkr9GVpOTSyPQoVLK5Wo9jqxkOZCyVMMmhAEK3bmbjYvsHLyv6vBnVwioJD9MHmUYPuNLj9fp3dKoiw25HMb2vIdI9B3nIkGJx6s3KFHztkTxI9tO0JqAtyvuNrGqnsq/yg8kxsf/bnwHIckEDrwD2kl9UWC8YIjiUS5jAPVGZf3Ga+s4GbqCfp1N+Wogp3caQtlCbS5IJjbznBzfXryPBZBDJpdalPReqT1doAmvNJYyHxPevqXqnaPPAIlssx+Cpy3IjYlgo6+essynBf+CC/EZMPCsGyaNZ3AoCGvrcueZ48NMbyJRwF9j120GX4VapB5lJUxR/guq79jzKpZHt1fRs0uBDGjsrC/Cddr+ih7YgE7eWZjVsYvV+Aqc51y1VEx41FKb5onZBijEVhWUIoNZSBGGi73WVdMLUVomWAvlHwR2EWQz+FeI9Lu+woKsw+cK6HF05veRPZYhnXGpHc1iRPn42qoZqxb87Sbt1t1XqP5+tte37CjiiWxriPhhEfTiRmJeiDRbzNFvOX/MbnHngdeD7GleA6Ev57Drww6YnGH3kUGUT2gDQ9AletiN9LA8b/veQLwvJdTYvSghk1EAbJ2eSqooZTfjw2pnILLk9dgFj/a9dtxv9yoC//yweqjUdn4ckIHd6bHviTNKalz+RyiuOXXorYAANrtyeZac9w0MZvpzz8xxI/P80M7Io6Lp3CxpczP/uPkrNiEyxs9fprYTM5GZaoo9aVmHyPMwfs+i5TasRWc0iuK6seh4QU5QjG1B/fcMsOvphD7RlVRyn9FHpGVh0jm6Q5zfqDitrruMx546CwLYRSfGK4UbCrPUvBc95D3rGPXBj5rDqwcH65DJpSH01tSQSIlXIq4mUc63iu6FNlwOyNM4IcvJeohRPhXZewwHy3UrrQdhHE6K06RGfttWtW+UwqWeBDEWtu2UMP9Wmq15gg2tTkbkG2n2R68psUPteTK4v5USSBXYEh7fepgEyxgu5oTBF94nKfeY7BvlyE0WPeH7/zhQz9OYGqvVDnlSYk4BpdmwtiQWRIair+MZa3IgkhoCdHH4axqwoXlvTaovhiT1Hbi/LTbSC5Ke9ngZ518AQx+901ft66OWCvlX+jLOx50Eu7ZsBx1iedZFeY12l3DIZMOcbexza73EmOBJNjNSqZgr/1ePpVMIcGsp0ULAuVKQIM0RSwqcrF16NOa3YNtYniE3XTQH1c63IbiQGO+H9344WCaFvprfEKaA1Ic00SQIRnwWnzyEIDMrsaEgBv10cSAzJ7k1Y1AAQbRwWxQcfjDSYkIO8bwjtWwYJprwBLR4fI7o5S1gtwxxsti+0MoTVF0ip7BMlcnKf5p436xeV2sX76fkp9lIqxAofljyozqEov+JyDwt/Lx5p54lTZl2cH6diqqgUfm1pfhcc9GFjCiIvWe+bVrVAa4aWKkGkPpkZp6AtOp+VUHkI/b1Lwz3pM9ogg3oTdRTlA+"
