steps:
  - group: ":open_book: Build & Deploy Documentation"
    if: build.message !~ /\[skip docs\]/ && !build.pull_request.draft
    steps:
      - label: "Tutorial Build [%N/%t] CUDA Runners"
        key: "tutorial-build-cuda"
        parallelism: 4
        plugins:
          - JuliaCI/julia#v1:
              version: "1"
        command: julia --code-coverage=user --color=yes --project=docs --threads=auto docs/tutorials.jl
        env:
          TUTORIAL_BACKEND_GROUP: "CUDA"
        agents:
          queue: "juliagpu"
          cuda: "*"
        artifact_paths:
          - "docs/src/tutorials/beginner/**/*"
          - "docs/src/tutorials/intermediate/**/*"
          - "docs/src/tutorials/advanced/**/*"
          - "tutorial_deps/*"
          - "**/*.cov"
        timeout_in_minutes: 120

      - label: "Tutorial Build [%N/%t] CPU Runners"
        if: build.message !~ /\[skip docs\]/ && !build.pull_request.draft
        key: "tutorial-build-cpu"
        parallelism: 4
        plugins:
          - JuliaCI/julia#v1:
              version: "1"
        command: julia --code-coverage=user --color=yes --project=docs --threads=auto docs/tutorials.jl
        env:
          TUTORIAL_BACKEND_GROUP: "CPU"
        agents:
          queue: "juliaecosystem"
          os: "linux"
          arch: "x86_64"
        artifact_paths:
          - "docs/src/tutorials/beginner/**/*"
          - "docs/src/tutorials/intermediate/**/*"
          - "docs/src/tutorials/advanced/**/*"
          - "tutorial_deps/*"
          - "**/*.cov"
        timeout_in_minutes: 120

      - label: "Final Documentation Build"
        depends_on:
          - "tutorial-build-cuda"
          - "tutorial-build-cpu"
        plugins:
          - JuliaCI/julia#v1:
              version: "1"
          - JuliaCI/julia-coverage#v1:
              codecov: true
              dirs:
                - src
                - ext
          - sv-oss/node-n#v0.1.2:
              node-version: v20
        command: |
          echo "+++ :node: Instantiate NPM"
          cd docs/
          npm i
          cd ..

          buildkite-agent artifact download "**/*" . --build $BUILDKITE_BUILD_ID

          julia --code-coverage=user --color=yes --project=docs -e '
            println("--- :julia: Instantiating project")
            using Pkg
            Pkg.instantiate()
            println("+++ :julia: Building documentation")
            include("docs/make.jl")'
        agents:
          queue: "juliagpu"
          cuda: "*"
        env:
          JULIA_DEBUG: "Documenter"
          LD_LIBRARY_PATH: ""
        timeout_in_minutes: 120

env:
  LUX_DOCUMENTATION_NTASKS: 1
  DATADEPS_ALWAYS_ACCEPT: true
  JULIA_PKG_SERVER: ""
  JULIA_NUM_THREADS: 4
  GKSwstype: "100" # https://discourse.julialang.org/t/generation-of-documentation-fails-qt-qpa-xcb-could-not-connect-to-display/60988
  SECRET_CODECOV_TOKEN: "jQ0BMTQgyZx7QGyU0Q2Ec7qB9mtE2q/tDu0FsfxvEG7/zOAGvXkyXrzIFFOQxvDoFcP+K2+hYZKMxicYdNqzr5wcxu505aNGN2GM3wyegAr+hO6q12bCFYx6qXzU9FLCCdeqINqn9gUSSOlGtWNFrbAlrTyz/D4Yo66TqBDzvaLL63FMnhCLaXW/zJt3hNuEAJaPY2O6Ze1rX2WZ3Y+i+s3uQ8aLImtoCJhPe8CRx+OhuYiTzGhynFfGntZ0738/1RN4gNM0S/hTC4gLE7XMVBanJpGh32rFaiDwW4zAyXKBrDkL3QA3MS1RvLTJxGJ085S16hCk0C4ddAhZCvIM9Q==;U2FsdGVkX1+bXdFeKMs5G79catOCyby2n07A2fg0FjVAvrjQLZ0yfvDS4paJiFikLkodho0khz2YALKb2Y0K6w=="
  SECRET_DOCUMENTER_KEY: "Fg0yDEszrqtbg3gl3odxpykZYDHb/dO2F391h6QBWxGkKNO6fmXgj8pt2OagSrnCjpXiIRv3q4YuVQUbY5ln19oNBxOHN0YY1YPtEzj3ve8fvpc4qIF+dCM25RHvCLravDS9yzifg6PCE9FCBAnw4drwZVFQF9GOuOmGfbHUS9H+YeXwTdFZQHSkjKk+uujmWjxgsOrHBjGRFgxZK5ZOuMi2KIk7VFJOmLcMisRIngrPVc44MWur96cYvDQlPYthCjFEThjZWiSkFcB5t5MVTZrD8NEbDRuCMREpyu7q/KFK2GOCcrv13fOAwAeraAK0jiCqdvCsEzcLwqqlhctOTQ==;U2FsdGVkX189SGcjuwWpLOiZrLAv49LwHOeZF2k0o0V8ydQT2fgD3dRwMcQkMGFDW3x0ANQk4k2a2zmc+MUQdbJq7GR1gLZM6V+YdCdUzfPKSq0gG8re4o1/96SovyyaooLmj8ZkWgX29ruYtDEt3nIAKeM+Yn0/2HiCGHoUO6c6ZgjsVoTMxXlAQ9mathTPqVpEqzi2fwSfmTPUKR/eKo8fpjGQA4rOhB4dXb1b29qtqoUN2NKehaQ5I1JuOsTStUm2BKEq+nQovou4QgZBXV8JEZFeCE/7ADoOhShZ3kq0DESuk4lbdBM33nI9xPFHRTZ5R/R7+4t2TUVJEE0MkJm3mn6nGNBvjUWzil7atC0zeFbdg9jJswiQDNGDquE8EcUp8oJgQOOZSgPnfdYeHc9pGWTh9yMWAXuQsFC3QSonOl4AFQxPH0pIPKZxEwtcOTGiXoiRYgbxT4jbeB+jYBpG9dT+yyAtbGhQgwpdv5A9U1D5Ln3LIILSsM5VsWvzQMiOQgSGhbZLnJpnqOTCwByk1rDAMJTW2SQmXicTfomaUAOC27AZQbeyhgTSUT8qEGImY8/EsMIJhCDwg/ic2ec8mHYD86yD9dNXbxsF+5tepMEIr00xdB+N/rVd0Qosxj5AMzbKoY5DwY8HlMbKqAyB9kMZq7mJhyZNUhZptuDC4ttY//6iJeRa9pETpU42wWHpg7Vn3JRUx56iOspwcVBGHmrT0VelpLUV+apUT7D8mACXlNtwADDzZL+fzFfmVmNJT3pV9ABm1GJFSavYoejj+Sk/y8sX1Vf+hF4xYYvwGgDMBw9xh7n2MAWCK38EWMSHTorzHHYT1Vs47m/fVxiQGodEluJqEH/Gft1SgCAlsVu75Q15uK83Vp6F483Oz1w91HG1SJGfgjQlCK1NK3/11omNF7N6Lkeyw2w/bdgHt5Da6knYjIRG17a27QorZVQ5fiPRqtxznyl4ICCRWkOCAgYB8esNWaMfdBxYZIqrXHKSFb8RE+uVtAcHbPw+N2d4wZR2o6gZ/OOZgymQ02BNh6+wiReb1Ff4HqcO4lGzrwxvfefqsBT5EF9/1Gn1nGZHPsD8GV1FA4gqNf8BWfeEW1V0AdBT9jhv9x0MePwI1SasXzXAVbagXwl973sbk3sHQugphcj0ynmCh6foMlsGP4QBlAmF2N/J/TWDzOoQiY5nS85o7jl+buqt5bIuXChOW9/+3Q8W2GQaCvV2KBNCC3gNV9azvUogE7JvAqrEcmz8I0/Zs7hzKmTZBjBKNH09ZYHmImLn3X3H/c+VN7HGl3sd68CICMho/ZhwWaHKYrxl6+006TUAOc2CNzZWMqMULkBYEUemqK8QE9yr65yyEJ0MatSZzEp4OfcJkCGGP4Cez3Qo/gKwF1HEeoXugpQU+zxD9CEsSLeoZTdKRAdpW4L3VcmxTiNIwgi6ig+JbdE7CZjPSdoU1SP34O0rQCT+Eoiwpbpok6iqQQcIjctZZ20YOz2PMMrdUj1cf/cMDJrgwVKoGPOU7pihtApdLLNp6+Ohk3uzLYi5sK0IslZjXnig3jQ/AygEFp/ZVmSSsod75I8kWrqyE7qQoDvE1CtKUBC4pwZEe8+91EPsumoz2+Jj88W2ZSIOEJJaGOMgPfIFksP9cFYdXR4y0ZfTVAmLZBKyMO+1BUS9nmReKacQRUUDLkpnREg81L5XqQIGm99kz7RS3NsRo5g+EGjqTiuSampguvvw/XNKxns4r08HbZQ2PYcq3LdnL2GFHPb3dLwhAnu8PLXRh5moL0Rl/VAUSZze8YFR9BH8mzW0e/0FFm1yqqCEiUpYEdUk+jAuNPYp9vQkSxefDOD95H0LlX8iHC0Q4HFrgzMyh/SnvuTibA13/N22/QyYDmtaa1x96P4i2VghjAiNCtTj+XwkbbYUHSHjBQHIrINi8zNO2qY6ajOQlr3e2oZfc9vNQrFqVAagi2l3d/gsKE4z8DG8GRao5NUcPoP15ERufvKjT4mGN2+FX55/AxtWqcOm/9iS7gmn1m/cUdYUkeBVqhlIsMXrN0K4gFwl4rAh1FtouMvFTQpRy0NfJ/OOKOZjsYi/56QhFMDkhZvUYKFJi0k3rDLe99s3mBaemprpgGkWRkGOhKvmN8MK8XRL2rFfKPc55CkRddzzOFc9c/rDrDGFIrsM2CjTBTwDuUymMfS60GERwutb+2nExDucNmCJykL45KRN6K77HyOvPnQasAdY1lN/J1qNxtjdP2jjyL+K80tQDjCsUdZ/kWa5n7cNUC2yea+ebYa9Jd+DAZTdeni1VIq+zXGlCRAC+jbTMnl7ZOdLlx0xQK5zvkknxUDBJ8BzoSDrGDZfVmQGJOqL2SzLtMZuI+TpqlfcCAZDq1JVDUCjuil/dSFjTBZDOZL30dcnq7RhhUJLceHnMyH3Dq8h4PEiFU8IqzZmeJcn4ttZAAcP8ijTC+JqOxDR3G2kDQas/ZNNJYcq4HpqHSZLRdlQDiqCDICsrD72j1pkEwKpiiB3hdbriVnCaUN0oLHKjLL2mD4N1v6/OgOJqabveYClwxEHIIfiVYq7kcMbCySEo9oMr0H5TbeUHA/RtGH1Hhex97j/5CRX3I/a5sGN/ZXBXCwIHIwhvPlmm95jTEh9lH376Cln7NCt1qfWj1HnbLNn11D+VBgGi5Gh/RroUUamUP73h6CimeBoGlUmvyYw1vJJVbLWuldU33xMeLjoeNmuM1VEtWIK7PTAliyPNYEvvAnYJUgseo4EIdlRb9XsJ+ZilKsCepl2iKwdJBW5CL0buTiUodKeGBfBFEu6Dy8eq9AXCtLgmXb92GiQPSspGfU5XBXZIhN2X4fdBNcLPBnURHjQlA59P1jbC8NT6iTvEiZmVAdGLNJXBUtPEvLrrvvdgr+k/t51RLrLguaC3KHH9XHvtLh71AToM5IZR1vqwuiGISTwl01GfGMN9bCMC/tzcYfG8JsjE894+KYaTetW6QWqTyGKEm7z30U3HXtgct0RzqMn2+T+jKgjK9LBZb49XadP5p3YMKaPJ8jW3F2tFj2n6SUSxam2R+2JgP9FUMxw7RKjLvlG3ufcllhwK04Nzn8OQ+NsYqvejzmNMNYwJpzBj/38k3wADx0+ATiTrXlbcjYoG4T8LYQfdgTRmeln5IkT/w5gzz3vVMng7q0A2+ijyvgC/csv+lScMJXB05BBymxlBYl8ndCWmCqlnEKA7vdn33uWOTmx1i028OE1Ax6KD+qynQcZfk6VK5vMJcmImQh4hEg+Cg/uGrkWbvP11sBgHV7mNAzix3tc+D7jyGcOzQL+XzKA9B+qoiUSw3yaSYRBjb1YsXw4nu56/2CVn0ONnO1Br5dXcsqG5F68CP7RuVj+PXwUKW87PjNqjkYZ0f6ctS+ExrzSVa02Avq1CVTeSrWDXJe4DUr+nEm+WgXuiTagBoz6zsfMJUljlF9IU6AsM8pPVP3Jo5/ymAUDogD3VV+Opp9csroNfegbp7BHzMUMsfj0ccZPU0KzyvODl3avL2qlILvlxN68bILeSAOLdrYBD12jJxoq3vtFzcWP1NquimuuT4VvU5Cy3ST0UzBJ3XCTnOHgRyN+4P85PvVlqpapOglZvRm8ZLLTohtr/ejeH3x4jKL21Z+twgRktS4mKWWECt3W95bav5x43QIilk/TjQjO2i6iqXvqWE6rDI4dlrIjnCHSqbB5A1V8kVuTMXYZvhApD9mrsfdZChdLPaXpdXLUjejT3VsxWofuHg/M2mv1dawX2jmir+B9nmk54Gp9AKDOr1r66YR4zHJApSJD3ZThcAV3as4fpySm87WAjGyweYssc2wzxCmDTXCZulK0YNHeAffsxaIhEro5NY06IUHp93eru+B4HkbHNXgMJnOG2hqYzMIQqcdDmLmiT7xi9M4MzJF8Wq+439IbvrqkmqgFpiJU+V/dqIYjqzweyZmkIAv6BhAWSsGo1nNYFgRasuDdbtxFViyJvWvxoGcOUAljys9iAB6sgL0UvKntfawfMCigfndyHyx0/aMI3Oe5TPy672OBGfOMeDaw3LjkfIErGKohIYCKu/UPL/yMaHQXrLTNH5PU0uWPsDqHk3fVW+5CGHyKCjJ+mTZIVA57cXZz1FznyyW/EHGD2i5AhqhBel2o5DIWzWac+CiNvAIOImxpvnnDREB38Np/JDtvCkcJauqpvlNQGeCqJLEP0ihZScWgzPuH+7mx2GgvSQUq89LzY7sAZXEPOljB0x8QRyllQaHL2ixT8asGgaw/DXXbw7iWJ8o56q4Z6ssUMDWVHqGz8hq67BLzwoUsiEQy3UEIxEhlvE9g8zTV6ah1YUq2z9IbQTwZ4oVDJjGxqJ5A2/19Q1+DjE+Rysn4HEeJzekw+BCdMDOqo8zmiwr8N1iAcxE57lKQ"
