steps:
  - group: ":julia: CUDA GPU"
    steps:
      - label: ":julia: Julia {{matrix.julia}} + {{matrix.testing_group}} + CUDA GPU"
        plugins:
          - JuliaCI/julia#v1:
              version: "{{matrix.julia}}"
          - JuliaCI/julia-test#v1:
              test_args: "--quickfail"
          - JuliaCI/julia-coverage#v1:
              codecov: true
              dirs:
                - src
                - ext
        agents:
          queue: "juliagpu"
          cuda: "*"
        env:
          BACKEND_GROUP: "CUDA"
          LUX_TEST_GROUP: "{{matrix.testing_group}}"
        if: build.message !~ /\[skip tests\]/ && build.message !~ /\[skip ci\]/
        timeout_in_minutes: 60
        matrix:
          setup:
            julia:
              - "1"
            testing_group:
              - "!distributed"
              - "distributed"

  - group: ":telescope: Downstream CUDA"
    steps:
      - label: ":julia: {{matrix.repo}} (Julia 1 + CUDA GPU)"
        plugins:
          - JuliaCI/julia#v1:
              version: "1"
          - JuliaCI/julia-coverage#v1:
              codecov: true
              dirs:
                - src
                - ext
        command: julia --code-coverage=user --color=yes --project .buildkite/scripts/downstream.jl "{{matrix.repo}}" "CUDA"
        agents:
          queue: "juliagpu"
          cuda: "*"
        env:
          RETESTITEMS_NWORKERS: 2
        if: build.message !~ /\[skip tests\]/ && build.message !~ /\[skip downstream\]/ && build.message !~ /\[skip ci\]/ && build.pull_request.labels includes "run downstream test"
        timeout_in_minutes: 60
        matrix:
          setup:
            repo:
              - "Boltz"
              - "NeuralPDE#GPU"
              - "DeepEquilibriumNetworks"

  - group: ":julia: AMD GPU"
    steps:
      - label: ":julia: Julia: {{matrix.julia}} + {{matrix.testing_group}} + AMD GPU"
        plugins:
          - JuliaCI/julia#v1:
              version: "{{matrix.julia}}"
          - JuliaCI/julia-test#v1:
              test_args: "--quickfail"
          - JuliaCI/julia-coverage#v1:
              codecov: true
              dirs:
                - src
                - ext
        env:
          JULIA_AMDGPU_CORE_MUST_LOAD: "1"
          JULIA_AMDGPU_HIP_MUST_LOAD: "1"
          JULIA_AMDGPU_DISABLE_ARTIFACTS: "1"
          BACKEND_GROUP: "AMDGPU"
          LUX_TEST_GROUP: "{{matrix.testing_group}}"
          RETESTITEMS_NWORKERS: 2
        agents:
          queue: "juliagpu"
          rocm: "*"
          rocmgpu: "*"
        if: build.message !~ /\[skip tests\]/ && build.message !~ /\[skip ci\]/
        timeout_in_minutes: 60
        matrix:
          setup:
            julia:
              - "1"
            testing_group:
              - "!distributed"
              - "distributed"

  - group: ":telescope: Downstream AMD GPU"
    steps:
      - label: ":julia: {{matrix.repo}} (Julia 1 + AMD GPU)"
        plugins:
          - JuliaCI/julia#v1:
              version: "1"
          - JuliaCI/julia-coverage#v1:
              codecov: true
              dirs:
                - src
                - ext
        command: julia --code-coverage=user --color=yes --project .buildkite/scripts/downstream.jl "{{matrix.repo}}" "AMDGPU"
        agents:
          queue: "juliagpu"
          rocm: "*"
          rocmgpu: "*"
        env:
          JULIA_AMDGPU_CORE_MUST_LOAD: "1"
          JULIA_AMDGPU_HIP_MUST_LOAD: "1"
          JULIA_AMDGPU_DISABLE_ARTIFACTS: "1"
        if: build.message !~ /\[skip tests\]/ && build.message !~ /\[skip downstream\]/ && build.message !~ /\[skip ci\]/ && build.pull_request.labels includes "run downstream test"
        timeout_in_minutes: 60
        matrix:
          setup:
            repo:
              - "Boltz"


env:
  JULIA_AMDGPU_LOGGING_ENABLED: true
  RETESTITEMS_NWORKERS: 8
  RETESTITEMS_NWORKER_THREADS: 2
  RETESTITEMS_TESTITEM_TIMEOUT: 3600
  JULIA_PKG_SERVER: ""
  JULIA_NUM_THREADS: 4
  SECRET_CODECOV_TOKEN: "jQ0BMTQgyZx7QGyU0Q2Ec7qB9mtE2q/tDu0FsfxvEG7/zOAGvXkyXrzIFFOQxvDoFcP+K2+hYZKMxicYdNqzr5wcxu505aNGN2GM3wyegAr+hO6q12bCFYx6qXzU9FLCCdeqINqn9gUSSOlGtWNFrbAlrTyz/D4Yo66TqBDzvaLL63FMnhCLaXW/zJt3hNuEAJaPY2O6Ze1rX2WZ3Y+i+s3uQ8aLImtoCJhPe8CRx+OhuYiTzGhynFfGntZ0738/1RN4gNM0S/hTC4gLE7XMVBanJpGh32rFaiDwW4zAyXKBrDkL3QA3MS1RvLTJxGJ085S16hCk0C4ddAhZCvIM9Q==;U2FsdGVkX1+bXdFeKMs5G79catOCyby2n07A2fg0FjVAvrjQLZ0yfvDS4paJiFikLkodho0khz2YALKb2Y0K6w=="
