# Non Differentiable Functions
CRC.@non_differentiable compute_adaptive_pooling_dims(::Any, ::Any)
CRC.@non_differentiable istraining(::Any)
CRC.@non_differentiable _get_norm_except_dims(::Any, ::Any)
CRC.@non_differentiable _affine(::Any)
CRC.@non_differentiable _track_stats(::Any)
CRC.@non_differentiable _conv_transpose_dims(::Any...)
CRC.@non_differentiable _calc_padding(::Any...)
CRC.@non_differentiable __set_refval!(::Any...)
CRC.@non_differentiable __state_if_stateful(::Any)
CRC.@non_differentiable __set_state!(::Any...)
CRC.@non_differentiable __update_bn_state(::Any...)
CRC.@non_differentiable __warn_mismatch(::Any...)
