name: CI Nightly
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        group:
          - Lux       # Core Framework
          - Boltz     # Prebuilt Models using Lux
          - LuxLib    # Backend of Lux
          - LuxCore   # Avoid the heavy Lux Dependency
          - LuxCUDA # Just test installation
          - LuxAMDGPU # Just test installation
        version:
          - 'nightly'  # merge even if tests fail
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
      - name: Run Tests
        run: julia --color=yes .ci/test.jl
        env:
          COVERAGE: "true"
          GROUP: ${{ matrix.group }}
          OVERRIDE_INTER_DEPENDENCIES: "false"
      - uses: julia-actions/julia-processcoverage@v1
        with:
          directories: src,lib/Boltz/src,lib/LuxLib/src,lib/LuxCore/src,ext,lib/LuxLib/ext,lib/LuxCUDA,lib/LuxAMDGPU
      - uses: codecov/codecov-action@v3
        with:
          files: lcov.info
          flags: ${{ matrix.group }}
